### ISSUE TITLE
NullReferenceException when pageReference is null

### ISSUE THREAD

**Issue by jw56** [cajuncoding/PdfTemplating.XslFO#13]
Hi,
I've just started to use the library but I am getting a NullReferenceException which appears to be because the pageReference is null and then added to the PdfArray in PdfGoTo Write method.

I think this is because it is set to null in IDNode CreateInternalLinkGoTo.

When it is set to null in this way, is the code expecting the pageReference to be set some other way after the instantiation of the PdfGoTo object?

It sounds like I may have a link to a document element that cannot be found? Any ideas how I can diagnose this?

Thanks,

John

**Comment by cajuncoding** [comment]
You mention `PdfGoto` method & `PdfArray` classes…these aren’t part of my library…are you looking in the `FONet` library code? 

That is mainly here for posterity and I don’t support it…

Though with that said, the FONet library does work and I have used it quite a bit in the past.  

So, you will have to provide some additional details on what you are doing, what does your Xsl-FO look like, which rendering engine are you using?  Provide sample code and XSL-FO markup, etc.

**Comment by jw56** [comment]
Ah, ok. I'll try and see if it is a known issue in the FONet library then. Thanks
